### ISSUE TITLE
Runtime Error in `main.py` also in `final_train.py`

### ISSUE THREAD

**Issue by pranv12** [otmhi/Bird-Image-Classification#1]
I tried running python final_train.py and getting the following error.

`all_train/
creating the final train dataset
Using CPU
Traceback (most recent call last):
  File "final_train.py", line 84, in <module>
    train(epoch)
  File "final_train.py", line 72, in train
    output = model(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 140, in forward
    return self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/Bird-Image-Classification/model.py", line 27, in forward
    f1, f2 = self.m1(x).view(-1,2048), self.m2(x).view(-1,2048)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/resnet.py", line 108, in forward
    out = self.conv3(out)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()

RuntimeError: DataLoader worker (pid 352) is killed by signal: Killed. `

P.S. At this point I just want the inference of model, without getting into much details about the model.

**Comment by pranv12** [comment]
Reducing the batch size worked for me
Hence closing the issue
